apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-fetcher-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-fetcher
  template:
    metadata:
      labels:
        app: image-fetcher
    spec:
      volumes:
        - name: shared-img
          persistentVolumeClaim:
            claimName: the-project-claim
      containers:
        - name: image-fetcher
          image: alxcd/devops_k8s-image-fetcher@sha256:df7e8d443da3847cd82de2fd878cc4f529c3d2eb0bbf1fed26a6208d0b32a9ed
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
          - name: shared-img
            mountPath: /usr/src/app/img
